modLoader = "javafml" #mandatory
loaderVersion = "[41,]" #mandatory
license = "MIT License"
credits = "" #optional
authors = "gigabit101" #optional
[[mods]] #mandatory
modId = "rebornstorage" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "RebornStorage" #mandatory
description = ''' A large multiblock that can store all of your crafting patterns in one place
'''

[[dependencies.rebornstorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.rebornstorage]]
modId = "refinedstorage"
mandatory = true
versionRange = "[1.11.0,)"
ordering = "AFTER"
side = "BOTH"
